### ISSUE TITLE
大佬，求同步一份到码云吧！便于star

### ISSUE THREAD

**Issue by misitebao** [kon9chunkit/GitHub-Chinese-Top-Charts#18]
QwQ

**Comment by WeChatTest001** [comment]
你也可以考虑把自己的项目放到 GitHub，两端同步。

[**提交自 GitHub Top 小程序**](https://github.com/renyuzhuo/GitHub-Top)

**Comment by kktao11** [comment]
你真的会给star吗，你这star都打错了

**Comment by oreoft** [comment]
> 你真的会给star吗，你这star都打错了

笑死我了, hhhhh

**Comment by kktao11** [comment]
@oreoft 哈哈哈哈哈哈

**Comment by pmerinfosafe** [comment]
所以现在已经变成一个群嘲了？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kon9chunkit/GitHub-Chinese-Top-Charts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 上午9:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [kon9chunkit/GitHub-Chinese-Top-Charts] 大佬，求同步一份到码云吧！便于start (#18)





  
你真的会给star吗，你这star都打错了
  
笑死我了, hhhhh
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 7xuaiyao521** [comment]
hhhh



***@***.***
 
发件人： 没有气的汽水
发送时间： 2021-11-19 09:58
收件人： kon9chunkit/GitHub-Chinese-Top-Charts
抄送： Subscribed
主题： Re: [kon9chunkit/GitHub-Chinese-Top-Charts] 大佬，求同步一份到码云吧！便于start (#18)
你真的会给star吗，你这star都打错了
笑死我了, hhhhh
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by misitebao** [comment]
唉！

**Comment by kon9chunkit** [comment]
> QwQ

已同步更新到码云，感谢你的建议。
